language: node_js
sudo: required

services:
  - docker
  
node_js:
  - "6.11"

before_install:
  - npm install -g envhandlebars
  - sudo apt-get install liblzo2-2 libvorbis0a libvorbisfile3 libvorbisenc2 libogg0 tree
  
script:
  - tree
  - chmod +x ./tools/bin/makepbo
  - export LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/tools/lib"
  - bash ./build/build.sh
  
before_deploy:
  - git config --local user.name "Travis Build"
  - git config --local user.email "build@travisci.org"
  - git tag "$(date +'%Y%m%d%H%M%S')-$TRAVIS_BRANCH"
  
deploy:
  all_branches: true
  provider: releases
  github_token: $GITHUB_TOKEN
  file_glob: true
  file: bin/*.pbo
  skip_cleanup: true

branches:
  only:
    - /.*/