language: node_js

services:
  - docker
  
node_js:
  - "6.11"

before_install:
  - npm install -g envhandlebars
  - chmod +x ./tools/makepbo
  
script:
  - bash ./build/build.sh

branches:
  only:
    - /.*/